apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-rag-config
  labels: {{- include "graph-rag.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
